### ISSUE TITLE
Loading RMySQL borks the RPostgreSQL driver

### ISSUE THREAD

**Issue by zachmayer** [rstats-db/RMySQL#28] opened 2015-01-07 14:21 UTC
Replicated on Fedora 20 and Mac OS X 10.9.5 (Mavericks):

```{R}
RMySQL::MySQL()
RPostgreSQL::PostgreSQL()
Error in as.integer(from) : 
  cannot coerce type 'S4' to vector of type 'integer'
```

This issue appears to be new to `RMySQL 0.10`, it is not  present in `RMySQL 0.9.3`.

**Comment by hadley** [comment] 2015-01-07 14:34
I just noticed this too :(  There was a problem with the old version too, but it only shows up if you load all of RMySQL, RSQLite and RPostgreSQL

**Comment by jeroenooms** [comment] 2015-01-16 06:07
This particular example seems to be caused by the [workaround](https://github.com/cran/RMySQL/blob/master/R/zzz_compatibility.R) that is currently in place to prevent the TSMySQL package from breaking. It alters the show method for `dbObjectId` objects in a way that does not work for `PostgreSQLDriver` objects. Not sure if this is the full story. Are there other cases?

**Comment by hadley** [comment] 2015-01-16 11:20
Ah yes, that's why I removed it in the first place. I think we can re-remove it, and let TSMySQL fix before next release.

**Comment by jeroenooms** [comment] 2015-01-16 17:55
It seems like the author of `TSMySQL` won't be able to push an update for several months, which is too long (BDR already requested another asap fix).

Is there a way we can hack around this without breaking things?

**Comment by hadley** [comment] 2015-01-16 18:01
Do you know how to elicit the problem with TSMySQL?

**Comment by jeroenooms** [comment] 2015-01-16 18:21
Its this one: https://github.com/rstats-db/RMySQL/issues/21.

**Comment by hadley** [comment] 2015-01-16 18:42
Do you happen to know what code triggers that error?

**Comment by hadley** [comment] 2015-02-16 14:11
Will be fixed in cpp branch

**Closed by hadley** 2015-02-16 14:11 UTC

**Comment by zachmayer** [comment] 2015-03-02 17:09
FYI to anyone showing up here after a google or github search: you can downgrade to RMySQL 9.3 (until the issue is fixed on the CRAN version):
```{R}
install.packages("http://cran.r-project.org/src/contrib/Archive/RMySQL/RMySQL_0.9-3.tar.gz", repos=NULL, type="source")```

**Comment by jeroenooms** [comment] 2015-04-22 17:38
@zachmayer I pushed a maintenance version to cran. Can you check if this resolves your problem?

**Comment by zachmayer** [comment] 2015-04-22 20:28
@jeroenooms Yup, it's fixed.  Thank you.
