### ISSUE TITLE
dbWriteTable got an error

### ISSUE THREAD

**Issue by funnng** [rstats-db/RMySQL#31] opened 2015-01-13 06:10 UTC
MariaDB 10.0

```
> con
<MySQLConnection:0,2>
> dbWriteTable(con, 'mtcars', mtcars)
Error in .local(conn, statement, ...) : 
sdbi1ab87df67117' not found (Errcode: 22)
```

**Comment by hadley** [comment] 2015-01-13 13:59
Can you please provide the results of `traceback()`?

**Comment by funnng** [comment] 2015-01-14 01:38
```
> dbWriteTable(con, 'mtcars', mtcars)
Error in .local(conn, statement, ...) : 
sdbi157472631829' not found (Errcode: 22)
> traceback()
13: .Call(RS_MySQL_exec, conn@Id, as.character(statement))
12: .local(conn, statement, ...)
11: is(object, Cl)
10: is(object, Cl)
9: .valueClassTest(standardGeneric("dbSendQuery"), "DBIResult", 
       "dbSendQuery")
8: dbSendQuery(conn, statement, ...)
7: dbGetQuery(conn, sql)
6: dbGetQuery(conn, sql)
5: .local(conn, name, value, ...)
4: is(object, Cl)
3: is(object, Cl)
2: .valueClassTest({
       standardGeneric("dbWriteTable")
   }, "logical", "dbWriteTable")
1: dbWriteTable(con, "mtcars", mtcars)
```

**Comment by hadley** [comment] 2015-01-16 16:49
Hmmm, I can't recreate this locally.  Does "sdbi1ab87df67117" mean anything to you?

**Comment by funnng** [comment] 2015-01-17 02:13
"sdbi1ab87df67117" change every time when i call `dbWriteTable` and it means nothing for me
```
> con
<MySQLConnection:0,0>
> dbWriteTable(con, 'mtcars', mtcars)
Error in .local(conn, statement, ...) : 
sdbi15ac41411c1' not found (Errcode: 22)
> dbListTables(con)
[1] "mtcars"
> dbGetQuery(con, 'select * from mtcars')
 [1] row_names mpg       cyl       disp      hp        drat      wt       
 [8] qsec      vs        am        gear      carb     
<0 rows> (or 0-length row.names)
```

**Comment by jeroenooms** [comment] 2015-01-17 02:19
Which operating system are you using for the client/server? Which version of R do you have?

**Comment by funnng** [comment] 2015-01-17 02:29
im using MariaDB on my windows 7 for test, and R  is `R version 3.1.2 (2014-10-31)`

```
MariaDB [(none)]> status
--------------
F:\MariaDB10\bin\mysql.exe  Ver 15.1 Distrib 10.0.15-MariaDB, for Win32 (x86)

Connection id:          11
Current database:
Current user:           root@localhost
SSL:                    Not in use
Using delimiter:        ;
Server:                 MariaDB
Server version:         10.0.15-MariaDB mariadb.org binary distribution
Protocol version:       10
Connection:             localhost via TCP/IP
Server characterset:    utf8
Db     characterset:    utf8
Client characterset:    gbk
Conn.  characterset:    gbk
TCP port:               3306
Uptime:                 49 min 23 sec

Threads: 6  Questions: 95  Slow queries: 0  Opens: 9  Flush tables: 1  Open tabl
es: 69  Queries per second avg: 0.032
```

```
> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          1.2                         
year           2014                        
month          10                          
day            31                          
svn rev        66913                       
language       R                           
version.string R version 3.1.2 (2014-10-31)
nickname       Pumpkin Helmet       
```

**Comment by hadley** [comment] 2015-02-17 15:16
I'm closing since I can't reproduce locally, and I'm about to implement a better strategy for inserting data

**Closed by hadley** 2015-02-17 15:16 UTC
