### ISSUE TITLE
same SQL get different results in RMySQL and MySQL client

### ISSUE THREAD

**Issue by funnng** [rstats-db/RMySQL#124] opened 2015-12-11 01:42 UTC
same SQL get different results in RMySQL and MySQL client.
```
CREATE TABLE `index_tableauuser` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(120) NOT NULL,
  `shop` longtext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

```
here is result of navicat:
![navicat](https://cloud.githubusercontent.com/assets/394134/11733697/2caad1c6-9feb-11e5-95b8-76db3ddc2bc2.png)

here is result of RMySQL:
```
> con <- dbConnect(RMySQL::MySQL(), groups = "bi")
> dbGetQuery(con,"SELECT id, name AS tableau_user, shop FROM index_tableauuser")
   id tableau_user       shop
1   1        admin           
2   2     初语集团           
3   3         茵曼 茵曼旗舰店
4   4         初语 茵曼旗舰店
5   5         秋売 茵曼旗舰店
6   6     生活在左 茵曼旗舰店
7   7       达丽坊 茵曼旗舰店
8   9       新品牌 茵曼旗舰店
9  10       五粒豆 茵曼旗舰店
10 11     茵曼集团 茵曼旗舰店
> con
<MySQLConnection>
  Host:   rdso12nbh93j.mysql.rds.aliyuncs.com via TCP/IP
  Server: 5.6.16-log
  Client: 5.5.44-MariaDB
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] assertthat_0.1     lubridate_1.3.3    tidyr_0.3.1        dplyr_0.4.3        shiny_0.12.2.9005  rJava_0.9-7       
[7] RMySQL_0.11.0.9000 DBI_0.3.1.9008    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.2     digest_0.6.8    mime_0.4        plyr_1.8.3      R6_2.1.1        xtable_1.7-4    magrittr_1.5   
 [8] stringi_1.0-1   tools_3.2.2     stringr_1.0.0   httpuv_1.3.3    parallel_3.2.2  memoise_0.2.1   htmltools_0.2.6
```

only the 3rd row of shop field has record, the other should be null, but it full with same string as from row 3

**Comment by funnng** [comment] 2015-12-11 02:05
`RMySQL_0.10.6` gets the right result on my local env.
i have `devtools::install_github("rstats-db/RMySQL#90")` this pull request since `RMySQL_0.10.6` can't connect with groups argument
```
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Chinese (Simplified)_People's Republic of China.936 
[2] LC_CTYPE=Chinese (Simplified)_People's Republic of China.936   
[3] LC_MONETARY=Chinese (Simplified)_People's Republic of China.936
[4] LC_NUMERIC=C                                                   
[5] LC_TIME=Chinese (Simplified)_People's Republic of China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMySQL_0.10.6 DBI_0.3.1    

loaded via a namespace (and not attached):
[1] tools_3.2.2
```

**Comment by krlmlr** [comment] 2015-12-11 08:03
Is this a duplicate of #65?

**Comment by funnng** [comment] 2015-12-11 08:10
seems the same problem.
it there a fix?

**Closed** 2015-12-16 22:35 UTC
