### ISSUE TITLE
SHOW COLUMNS call yield incorrect information

### ISSUE THREAD

**Issue by Tutuchan** [rstats-db/RMySQL#87] opened 2015-08-05 17:10 UTC
Hi again,

I encountered another problem with the most recent version of RMySQL, namely that a ` SHOW COLUMNS` call will yield incorrect information on the columns of a database : 
```r
d> conn
<MySQLConnection>
  Host:   192.168.254.90 via TCP/IP
  Server: 5.6.24
  Client: 5.5.44
d> dbGetQuery(conn, "SHOW COLUMNS FROM stat__test")
  Field         Type Null Key Default          Extra
1    id      int(11)   NO PRI    <NA> auto_increment
2 value varchar(255)  YES PRI    <NA> auto_increment
```
Both columns appear as primary keys with auto_increment which is incorrect as the table was created with : 
```sql
CREATE TABLE `stat__test` ( `id` INT NOT NULL AUTO_INCREMENT , `value` VARCHAR(255) NULL 
DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
```

If I create a new table like this : 
```sql
CREATE TABLE `stat__test2` ( `test` INT(11) NOT NULL , `id` INT(11) NOT NULL 
AUTO_INCREMENT , `test2` INT(11) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
```

I get the following results : 
```r 
d> dbGetQuery(conn, "SHOW COLUMNS FROM stat__test2")
  Field    Type Null Key Default          Extra
1  test int(11)   NO        <NA>               
2    id int(11)   NO PRI    <NA> auto_increment
3 test2 int(11)   NO PRI    <NA> auto_increment
```
It appears that the Key and Extra information are propagated to the following columns ?

My session info is : 
```r
d> session_info()
Session info -----------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.1 (2015-06-18)
 system   x86_64, linux-gnu           
 ui       RStudio (0.99.441)          
 language (EN)                        
 collate  fr_FR.UTF-8                 
 tz       <NA>                        

Packages --------------------------------------------------------------------------------------------
 package    * version     date       source                           
 assertthat * 0.1         2013-12-06 CRAN (R 3.1.2)                   
 DBI          0.3.1.9008  2015-08-05 Github (rstats-db/DBI@f5bd553)   
 devtools     1.7.0       2015-01-17 CRAN (R 3.1.3)                   
 dplyr      * 0.4.2.9002  2015-08-05 Github (hadley/dplyr@a0cb303)                
 magrittr     1.5         2014-11-22 CRAN (R 3.1.2)                   
 R6         * 2.1.0       2015-07-28 Github (wch/R6@b3616a6)          
 Rcpp       * 0.11.6      2015-05-01 CRAN (R 3.2.0)                   
 RMySQL       0.11.0.9000 2015-08-05 Github (rstats-db/RMySQL@60ccc52)
 rstudioapi * 0.2         2014-12-31 CRAN (R 3.1.2)   
```
This was working correctly with version 0.10.2 : 
```r
d> session_info()
Session info ----------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.1 (2015-06-18)
 system   x86_64, linux-gnu           
 ui       RStudio (0.99.441)          
 language (EN)                        
 collate  fr_FR.UTF-8                 
 tz       <NA>                        

Packages --------------------------------------------------------------------------------------------------------------------------------------------------------------
 package    * version    date       source                       
 assertthat * 0.1        2013-12-06 CRAN (R 3.1.2)               
 DBI          0.3.1      2014-09-24 CRAN (R 3.1.2)               
 devtools     1.7.0      2015-01-17 CRAN (R 3.1.3)               
 dplyr      * 0.4.2.9002 2015-08-05 Github (hadley/dplyr@a0cb303)                    
 magrittr     1.5        2014-11-22 CRAN (R 3.1.2)               
 R6         * 2.1.0      2015-07-28 Github (wch/R6@b3616a6)      
 Rcpp       * 0.11.6     2015-05-01 CRAN (R 3.2.0)               
 RMySQL       0.10.2     2015-02-24 CRAN (R 3.1.2)               
 rstudioapi * 0.2        2014-12-31 CRAN (R 3.1.2)               
d> dbGetQuery(conn, "SHOW COLUMNS FROM stat__test2")
  Field    Type Null Key Default          Extra
1  test int(11)   NO        <NA>               
2    id int(11)   NO PRI    <NA> auto_increment
3 test2 int(11)   NO        <NA>
```

**Comment by krlmlr** [comment] 2015-10-27 19:29
Thanks, I can replicate this issue.

**Comment by krlmlr** [comment] 2015-10-27 19:43
Is this a dupe of #65?

**Comment by Tutuchan** [comment] 2015-10-28 09:53
Hi Kirill,

It might be, I am by no means familiar with the implementation of the MySQL driver.

**Closed** 2015-12-16 22:35 UTC
Labels: branch:master
