### ISSUE TITLE
Result object still in use after failed dbGetQuery

### ISSUE THREAD

**Issue by drknexus** [rstats-db/RMySQL#73] opened 2015-06-13 23:01 UTC
Short version:  It seems that when a query fails (due to user error) the result object stays in use.

This bug report falls more in the category of protecting the user from themselves rather than a full fledged bug.  Consider the sample code:
```
library(RMySQL)
con <- dbConnect(MySQL(), host=getOption("masterMySQLhost"), 
                 port=3306,
                 user=getOption("masterMySQLhost.username"),
                 password=getOption("masterMySQLhost.password"))
dbGetQuery(con,"SELECT * FROM keyValue.missingTable")
dbDisconnect(con)
```
The query fails because there is no such table.  It helpfully throws an error to let you know that something was wrong:
```
Error: Table 'keyValue.missingTable' doesn't exist [1146]
```
 But, let's say we're fine that sometime that table won't be there (and we don't want to incur the cost of always checking whether it will be there).  We might do error catching on the Query but plan to `dbDisconnect` as normal.  dbDisconnect will provide a warning:
```
> dbDisconnect(con)
[1] TRUE
Warning message:
In connection_release(conn@ptr) : There is a result object still in use.
The connection will be automatically released when it is closed
```

Well... that's great, I just closed the connection with dbDisconnect, no?  Apparently not.  Consider:
```
replicate(1000,{
  con <- dbConnect(MySQL(), host=getOption("masterMySQLhost"), 
                   port=3306,
                   user=getOption("masterMySQLhost.username"),
                   password=getOption("masterMySQLhost.password"))  
  try(res <- dbGetQuery(con,"SELECT * FROM keyValue.missingTable"))
  dbDisconnect(con)
})
```
Which will eventually fail with: `Error: Failed to connect: Too many connections`.  At which point that R session isn't able to interact with the MySQL database further.

Bug report sessionInfo():
```
R version 3.2.0 (2015-04-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMySQL_0.11.0.9000 DBI_0.3.1.9008  
```

**Comment by krlmlr** [comment] 2015-10-27 19:38
Thanks. I'm seeing this, too.

**Comment by krlmlr** [comment] 2015-10-27 19:50
This looks like a dupe of #50.

**Closed** 2015-11-06 22:14 UTC
