### ISSUE TITLE
Date type returned for date fields in MySQL are inconsistents with R Date types

### ISSUE THREAD

**Issue by Tutuchan** [rstats-db/RMySQL#86] opened 2015-08-05 12:58 UTC
Hi,

From https://github.com/hadley/dplyr/issues/1303.

I don't have an open MySQL instance to showcase this but the fields of type `DATE` returned from a MySQL database use integers and not numerics. 

Here is some data returned from our work database where date is stored as a DATE field: 
```r
d> dput(dfDB)
structure(list(date = structure(16436:16440, class = "Date"), 
    value = c(1.2, 6.1, 7.4, 4.1, 0.1)), .Names = c("date", "value"
), class = "data.frame", row.names = c(NA, -5L))
d> dput(dfDB$date[1])
structure(16436L, class = "Date")
```
Here is a data.frame created in R:

```r
d> dfR <- data.frame(date = as.Date(c("2015-01-01", "2015-01-02", "2015-01-03", 
+                                    "2015-01-04", "2015-01-05")), value2 = 1:5)
d> dfR
        date value2
1 2015-01-01      1
2 2015-01-02      2
3 2015-01-03      3
4 2015-01-04      4
5 2015-01-05      5
d> dput(dfR$date[1])
structure(16436, class = "Date")
```
My session info :
```r
d> session_info()
Session info -----------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.1 (2015-06-18)
 system   x86_64, linux-gnu           
 ui       RStudio (0.99.441)          
 language (EN)                        
 collate  fr_FR.UTF-8                 
 tz       <NA>                        

Packages --------------------------------------------------------------------------------------------------
 package    * version     date       source                              
 assertthat * 0.1         2013-12-06 CRAN (R 3.1.2)                      
 bitops     * 1.0-6       2013-08-17 CRAN (R 3.1.2)                      
 curl       * 0.5         2015-02-01 CRAN (R 3.1.3)                      
 DBI        * 0.3.1.9008  2015-08-05 Github (rstats-db/DBI@f5bd553)      
 devtools     1.7.0       2015-01-17 CRAN (R 3.1.3)                      
 digest     * 0.6.8       2014-12-31 CRAN (R 3.1.2)                      
 dplyr        0.4.2.9002  2015-08-05 Github (hadley/dplyr@a0cb303)                      
 httr       * 0.6.1       2015-01-01 CRAN (R 3.1.2)                      
 jsonlite   * 0.9.16.9000 2015-06-19 Github (jeroenooms/jsonlite@4e2768d)
 knitr      * 1.10.5      2015-05-06 CRAN (R 3.2.1)                      
 lazyeval   * 0.1.10      2015-01-02 CRAN (R 3.1.2)                      
 magrittr     1.5         2014-11-22 CRAN (R 3.1.2)                      
 memoise    * 0.2.1       2014-04-22 CRAN (R 3.1.2)                      
 R6         * 2.1.0       2015-07-28 Github (wch/R6@b3616a6)             
 Rcpp       * 0.11.6      2015-05-01 CRAN (R 3.2.0)                      
 RCurl      * 1.95-4.5    2014-12-28 CRAN (R 3.1.2)                      
 RMySQL     * 0.11.0.9000 2015-08-05 Github (rstats-db/RMySQL@60ccc52)   
 rstudioapi * 0.2         2014-12-31 CRAN (R 3.1.2)                      
 stringi    * 0.4-1       2014-12-14 CRAN (R 3.1.2)                      
 stringr    * 1.0.0       2015-04-30 CRAN (R 3.2.1)                      
 testthat     0.9.1       2014-10-01 CRAN (R 3.1.2)
```

**Comment by krlmlr** [comment] 2015-10-27 19:33
But this works for me for date literals:

```
dput(dbGetQuery(con, "select cast('2011-11-11' as date)"))
## structure(list(`cast('2011-11-11' as date)` = structure(15289L, class = "Date")), .Names = cast('2011-11-11' as date)", class = "data.frame", row.names = c(NA,  -1L))
```

Could you please show a reproducible example?

**Comment by Tutuchan** [comment] 2015-10-28 09:51
Hi Kirill,

Thanks for taking the time to review this. I believe you see the same behavior as I do : the value of the date is encoded as an integer, instead of a numeric in base R.
```r
dput(as.Date("2011-11-11"))
structure(15289, class = "Date")
``` 
while you obtained from MySQL 
```r 
structure(15289L, class = "Date")
```
If we use identical on the result of your query, we can see it's not in the proper format : 
```r
df <- structure(list(`cast('2011-11-11' as date)` = structure(15289L, class = "Date")), .Names = "cast('2011-11-11' as date)", class = "data.frame", row.names = c(NA,  -1L))
identical(df[1,1], as.Date("2011-11-11"))
[1] FALSE
```

**Comment by krlmlr** [comment] 2015-10-28 09:59
Thanks for pointing me to the right direction. I think we want to ensure that the dates returned by RMySQL are consistent with what `as.Date()` returns.

**Comment by hadley** [comment] 2015-10-28 12:55
@krlmlr unfortunately R itself is not consistent - Dates can either be integers or doubles.

**Comment by krlmlr** [comment] 2015-10-28 13:33
Then we probably should reopen hadley/dplyr#1303 -- for instance, `readr` also seems to create dates as integers.

```
readr::read_csv(pipe("echo a; echo 2015-10-28")) %>% dput
## structure(list(a = structure(16736L, class = "Date")), class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, -1L), .Names = "a")
```

**Comment by hadley** [comment] 2015-10-28 13:37
I'm pretty sure we fixed that behaviour once I realised that it was common for dates (and date times) to be integers or doubles. This works for me:

```R
library(dplyr)
df1 <- data_frame(x = structure(1L, class = "Date"), y = 1)
df2 <- data_frame(x = structure(1, class = "Date"), z = 1)

left_join(df1, df2)
```

(FWIW you should never use `data.frame()` for tests like this because it does a lot of class munging in the background)

**Comment by krlmlr** [comment] 2015-10-28 13:46
@Tutuchan: Can we close this issue, if the dplyr joins work now for integer vs. numeric dates?

**Comment by Tutuchan** [comment] 2015-10-28 14:58
It's fine by me, this was the reason I opened the ticket here in the first place :).

**Closed** 2015-10-28 22:48 UTC
