### ISSUE TITLE
Unsigned INTEGER in col 0 imported as numeric

### ISSUE THREAD

**Issue by xizhiming** [rstats-db/RMySQL#69] opened 2015-05-11 14:27 UTC
Unsigned INTEGER in col 0 imported as numeric

**Comment by hadley** [comment] 2015-05-11 14:28
Please provide a reproducible example

**Comment by shadiakiki1986** [comment] 2016-02-01 11:24
Here's a reproducible example.

MySQL queries to create a test table:

```
create database if not exists rstats_db_issue69;
use rstats_db_issue69;
CREATE TABLE test (
  `id` int(10) unsigned NOT NULL auto_increment,
  `ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(255) NOT NULL,
  `job` VARCHAR(255) NULL,
  UNIQUE KEY `id` (`id`),
  KEY `name` (`name`),
  KEY `ts` (`ts`)
);

INSERT INTO test (name,job) VALUES ('Tarzan','Opera singer');
INSERT INTO test (name,job) VALUES ('James Bond','Secret agent');
```

R code that generates the warning
```
library(RMySQL)
m<-dbDriver("MySQL");
user="username" # insert username here
pass = "password" # insert password here
host = "localhost" # insert IP here
myconn<-dbConnect(m,user=user,password=pass,host=host,dbname="rstats_db_issue69");
adt<-dbGetQuery(myconn, "select * from test") # generates the warnings below
# Warning messages:
# 1: In .local(conn, statement, ...) :
#  Unsigned INTEGER in col 0 imported as numeric
#2: In .local(conn, statement, ...) :
#  unrecognized MySQL field type 7 in column 1 imported as character
dbDisconnect(myconn)
```

**Comment by krlmlr** [comment] 2016-02-05 09:49
Duplicate of #37. Please install the dev version using `devtools::install_github("rstats-db/RMySQL")` to avoid the warnings.

**Closed by krlmlr** 2016-02-05 09:49 UTC
