### ISSUE TITLE
dbWriteTable: corrupt resultSet, missing fieldDescription

### ISSUE THREAD

**Issue by alextosta** [rstats-db/RMySQL#140] opened 2016-03-11 22:12 UTC
Hi colleagues,

`example<-data.frame( Col1 = c(1,1) , Col2 = c(2,2))
drv<-dbDriver("MySQL")
con<-dbConnect(drv,dbname="metas",user="XXX",password="YYY",
               host="ZZZ")`

Everything goes allright until I try to write a data frame in the mySQL data base with the code:

`dbWriteTable(conn=con,"mysql_example",example,row.names=FALSE,overwrite=TRUE,append=FALSE)`

Then the following error message appears:

**Error in dbFetch(rs, n = -1, ...) : corrupt resultSet, missing fieldDescription**

Is there any problem with the code?

Thanks

**Comment by krlmlr** [comment] 2016-03-29 17:03
Duplicate of #141 and #53. "Stable" RMySQL is currently not compatible with "development" DBI, please either install RMySQL from GitHub or revert to the CRAN version of DBI.

**Closed** 2016-03-29 17:47 UTC
Labels: branch:stable
