### ISSUE TITLE
Validate dbConnect() parameters

### ISSUE THREAD

**Issue by stevenpollack** [rstats-db/RMySQL#56] opened 2015-03-11 21:31 UTC
Same setup as with issue #55 except my `~/.my.cnf` now is a bit more complicated:

```
[mysql]
database=algo
host=so1db.cjvo6rncstds.eu-west-1.rds.amazonaws.com
port=3306
user=so1engine
password=fakepassword123456789
```

and now when I reference the `mysql` group in `dbConnect`:

``` R
> X <- dbConnect(RMySQL::MySQL(), groups="mysql")
Error: Failed to connect: Access denied for user 'so1engine'@'c-24-12-233-98.hsd1.il.comcast.net' (using password: NO)

Enter a frame number, or 0 to exit

1: dbConnect(RMySQL::MySQL(), groups = "mysql")
2: .valueClassTest(standardGeneric("dbConnect"), "DBIConnection", "dbConnect")
3: is(object, Cl)
4: is(object, Cl)
5: .local(drv, ...)
6: connection_create(host, username, password, dbname, port, unix.socket, client.flag, groups, default.file)
```

I know the `~/.my.cnf` is proper, since I can call `mysql` and perform queries without issues:

``` MySQL
$ mysql
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 79090
Server version: 5.6.21-log MySQL Community Server (GPL)

Copyright (c) 2000, 2014, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SHOW DATABASES;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| algo               |
| campaigns          |
| loyalty            |
| masters            |
| reporting          |
| segment            |
+--------------------+
7 rows in set (0.13 sec)
```

Furthermore, when I try to fully qualify my call to `dbConnect`, I get an even weirder error, "Error: not compatible with requested type":

``` R
> X <- dbConnect(drv =RMySQL::MySQL(),
+        dbname='algo',
+        host='so1db.cjvo6rncstds.eu-west-1.rds.amazonaws.com',
+        port='3306',
+        user='so1engine',
+        password='fakepassword123456789')
Error: not compatible with requested type

Enter a frame number, or 0 to exit

1: dbConnect(drv = RMySQL::MySQL(), dbname = "algo", host = "so1db.cjvo6rncstds.eu-west-1.rds.amazonaws.com", port = "3306", user = "so1engine", password = "
2: .valueClassTest(standardGeneric("dbConnect"), "DBIConnection", "dbConnect")
3: is(object, Cl)
4: is(object, Cl)
5: .local(drv, ...)
6: connection_create(host, username, password, dbname, port, unix.socket, client.flag, groups, default.file)
```

**Comment by peternowee** [comment] 2015-10-01 15:32
The first part of this issue is a duplicate of #55.

With regard to the second part:

    Error: not compatible with requested type

This seems to be Rcpp complaining about the `port` parameter being a
string, where it was expecting a numeric. I am able to reproduce the
issue and solve it by using `port=3306` instead of `port='3306'`.

Current stable (RMySQL 0.10.6) also requires an integer, though it
gives a clearer error message:

    Error in .local(drv, ...) : Argument port must be an integer value

**Comment by krlmlr** [comment] 2015-11-11 10:49
Can we close this?

**Comment by peternowee** [comment] 2015-11-12 12:16
I think the main point left open here is that parameters of `dbConnect()`, such as `port`, are not validated by RMySQL itself anymore, as [they were in version 0.10.7][1], resulting in vaguer error messages from Rcpp in case the end user makes a mistake.

Perhaps this issue could be retitled to something like "dbConnect() parameters should be validated".

[1]: https://github.com/rstats-db/RMySQL/blob/v0.10.7/R/connection.R#L83

**Comment by krlmlr** [comment] 2015-11-12 12:21
I don't see a reason why a string that looks like an integer shouldn't be coerced to an integer. Other than that, I think the errors emitted by the MySQL driver should be fine in most cases.

**Comment by krlmlr** [comment] 2017-07-05 15:55
Moved to rstats-db/RMariaDB (see link above).

**Closed by krlmlr** 2017-07-05 15:55 UTC
Labels: branch:master
